name: CD - Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
      deployment_strategy:
        description: 'Deployment strategy'
        required: true
        type: choice
        options:
          - rolling
          - blue-green
          - canary

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  HELM_VERSION: v3.13.0
  KUBECTL_VERSION: v1.28.0

jobs:
  # ===========================================================================
  # Deploy to Development
  # ===========================================================================
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.event.inputs.environment == 'dev'
    environment:
      name: development
      url: https://dev.llmdevops.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name llm-copilot-dev --region us-east-1

      - name: Deploy with Helm
        run: |
          helm upgrade --install llm-copilot-agent \
            ./deployment/helm/llm-copilot-agent \
            --namespace llm-copilot \
            --create-namespace \
            --values ./deployment/helm/llm-copilot-agent/values-dev.yaml \
            --set image.tag=${{ github.sha }} \
            --wait --timeout 10m

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/llm-copilot-agent -n llm-copilot
          kubectl get pods -n llm-copilot -l app=llm-copilot-agent

  # ===========================================================================
  # Deploy to Staging
  # ===========================================================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'staging'
    environment:
      name: staging
      url: https://staging.llmdevops.io
    needs: []
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name llm-copilot-staging --region us-east-1

      - name: Deploy with Helm
        run: |
          helm upgrade --install llm-copilot-agent \
            ./deployment/helm/llm-copilot-agent \
            --namespace llm-copilot \
            --create-namespace \
            --values ./deployment/helm/llm-copilot-agent/values-staging.yaml \
            --set image.tag=${{ github.sha }} \
            --wait --timeout 10m

      - name: Run smoke tests
        run: |
          kubectl run smoke-test --rm -i --restart=Never \
            --image=curlimages/curl:latest \
            -- curl -f http://llm-copilot-agent.llm-copilot.svc.cluster.local/health

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/llm-copilot-agent -n llm-copilot

  # ===========================================================================
  # Deploy to Production (Blue-Green)
  # ===========================================================================
  deploy-production-blue-green:
    name: Deploy to Production (Blue-Green)
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && (github.event.inputs.deployment_strategy == 'blue-green' || github.event.inputs.deployment_strategy == '')
    environment:
      name: production
      url: https://api.llmdevops.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name llm-copilot-prod --region us-east-1

      - name: Get current active color
        id: get-color
        run: |
          CURRENT=$(kubectl get service llm-copilot-agent -n llm-copilot -o jsonpath='{.spec.selector.color}')
          if [ "$CURRENT" = "blue" ]; then
            echo "new_color=green" >> $GITHUB_OUTPUT
            echo "old_color=blue" >> $GITHUB_OUTPUT
          else
            echo "new_color=blue" >> $GITHUB_OUTPUT
            echo "old_color=green" >> $GITHUB_OUTPUT
          fi

      - name: Deploy new version (Green/Blue)
        run: |
          helm upgrade --install llm-copilot-agent-${{ steps.get-color.outputs.new_color }} \
            ./deployment/helm/llm-copilot-agent \
            --namespace llm-copilot \
            --values ./deployment/helm/llm-copilot-agent/values-production.yaml \
            --set image.tag=${{ github.sha }} \
            --set color=${{ steps.get-color.outputs.new_color }} \
            --wait --timeout 10m

      - name: Run smoke tests on new deployment
        run: |
          kubectl run smoke-test-${{ steps.get-color.outputs.new_color }} --rm -i --restart=Never \
            --image=curlimages/curl:latest \
            -- curl -f http://llm-copilot-agent-${{ steps.get-color.outputs.new_color }}.llm-copilot.svc.cluster.local/health

      - name: Run integration tests
        run: |
          kubectl run integration-test --rm -i --restart=Never \
            --image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --env="TARGET_URL=http://llm-copilot-agent-${{ steps.get-color.outputs.new_color }}.llm-copilot.svc.cluster.local" \
            -- npm run test:integration:production

      - name: Switch traffic to new version
        run: |
          kubectl patch service llm-copilot-agent -n llm-copilot \
            -p '{"spec":{"selector":{"color":"${{ steps.get-color.outputs.new_color }}"}}}'

      - name: Monitor new deployment
        run: |
          sleep 300  # Monitor for 5 minutes
          ERROR_RATE=$(kubectl exec -n observability deploy/prometheus -- \
            wget -qO- 'http://localhost:9090/api/v1/query?query=sum(rate(http_requests_total{job="llm-copilot-agent",status=~"5.."}[5m]))/sum(rate(http_requests_total{job="llm-copilot-agent"}[5m]))' \
            | jq -r '.data.result[0].value[1]')

          if (( $(echo "$ERROR_RATE > 0.05" | bc -l) )); then
            echo "Error rate too high: $ERROR_RATE"
            exit 1
          fi

      - name: Cleanup old deployment
        if: success()
        run: |
          helm uninstall llm-copilot-agent-${{ steps.get-color.outputs.old_color }} -n llm-copilot

      - name: Rollback on failure
        if: failure()
        run: |
          kubectl patch service llm-copilot-agent -n llm-copilot \
            -p '{"spec":{"selector":{"color":"${{ steps.get-color.outputs.old_color }}"}}}'
          helm uninstall llm-copilot-agent-${{ steps.get-color.outputs.new_color }} -n llm-copilot

  # ===========================================================================
  # Deploy to Production (Canary)
  # ===========================================================================
  deploy-production-canary:
    name: Deploy to Production (Canary)
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && github.event.inputs.deployment_strategy == 'canary'
    environment:
      name: production
      url: https://api.llmdevops.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name llm-copilot-prod --region us-east-1

      - name: Deploy canary (10% traffic)
        run: |
          kubectl apply -f - <<EOF
          apiVersion: networking.istio.io/v1beta1
          kind: VirtualService
          metadata:
            name: llm-copilot-agent-canary
            namespace: llm-copilot
          spec:
            hosts:
              - llm-copilot-agent
            http:
              - match:
                  - headers:
                      canary:
                        exact: "true"
                route:
                  - destination:
                      host: llm-copilot-agent
                      subset: canary
              - route:
                  - destination:
                      host: llm-copilot-agent
                      subset: stable
                    weight: 90
                  - destination:
                      host: llm-copilot-agent
                      subset: canary
                    weight: 10
          EOF

      - name: Monitor canary metrics
        run: |
          for i in {1..6}; do
            echo "Monitoring iteration $i/6..."
            sleep 300  # 5 minutes

            # Check error rate
            ERROR_RATE=$(kubectl exec -n observability deploy/prometheus -- \
              wget -qO- 'http://localhost:9090/api/v1/query?query=sum(rate(http_requests_total{job="llm-copilot-agent",version="canary",status=~"5.."}[5m]))/sum(rate(http_requests_total{job="llm-copilot-agent",version="canary"}[5m]))' \
              | jq -r '.data.result[0].value[1]')

            if (( $(echo "$ERROR_RATE > 0.05" | bc -l) )); then
              echo "Canary error rate too high: $ERROR_RATE"
              exit 1
            fi
          done

      - name: Promote canary to stable
        if: success()
        run: |
          kubectl apply -f - <<EOF
          apiVersion: networking.istio.io/v1beta1
          kind: VirtualService
          metadata:
            name: llm-copilot-agent-canary
            namespace: llm-copilot
          spec:
            hosts:
              - llm-copilot-agent
            http:
              - route:
                  - destination:
                      host: llm-copilot-agent
                      subset: canary
                    weight: 100
          EOF

          # Update stable deployment
          kubectl set image deployment/llm-copilot-agent \
            llm-copilot-agent=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -n llm-copilot

      - name: Rollback canary on failure
        if: failure()
        run: |
          kubectl apply -f - <<EOF
          apiVersion: networking.istio.io/v1beta1
          kind: VirtualService
          metadata:
            name: llm-copilot-agent-canary
            namespace: llm-copilot
          spec:
            hosts:
              - llm-copilot-agent
            http:
              - route:
                  - destination:
                      host: llm-copilot-agent
                      subset: stable
                    weight: 100
          EOF

  # ===========================================================================
  # Notify Deployment
  # ===========================================================================
  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy-production-blue-green, deploy-production-canary]
    if: always()
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Deployment ${{ needs.deploy-production-blue-green.result || needs.deploy-production-canary.result }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "LLM CoPilot Agent deployment *${{ needs.deploy-production-blue-green.result || needs.deploy-production-canary.result }}*\nVersion: `${{ github.sha }}`\nEnvironment: Production"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
